# CONTENU CORRECT pour le fichier netlify.toml
[build]
  command = "npm run build"
  publish = ".next" 

[build.environment]
  NODE_VERSION = "20" 

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"